name: Continuous Delivery

jobs:
    name: Build and push the docker image
    runs-on: ubuntu-latest
    needs: Build and test
    steps:
     - name: Build the docker image
     - uses: actions/checkout@v3
     - run:  docker build --tag branch_1 .

     - name: Tag the image to the docker repo
     - run: docker tag branch_1 mitub22/dotnettemplate:branch_1

     - name: Login to Docker
     - run: docker login --username=${{ secrets.DOCKER_USER }} --password=${{ secrets.DOCKER_PASSWORD }}

     - name: Push the docker image
     - run:  docker push mitub22/dotnettemplate:branch_1